// Downloadable report report.js
function formatQA(title, qaArray){
  const lines = [];
  lines.push(title);
  qaArray.forEach(x=>{
    lines.push(`- Question: ${x.q}`);
    lines.push(`  Response: ${x.a || "(no response)"}`);
  });
  lines.push("");
  return lines.join("\n");
}

function buildTxtSummary(){
  const lines = [];
  lines.push("Dark Blue Reset – Day 1");
  lines.push(`Date: ${new Date().toLocaleString()}`);

  if (dayMeta.userProfile){
    lines.push("");
    lines.push("Profile");
    lines.push(`- Name: ${dayMeta.userProfile.name || "-"}`);
    lines.push(`- Energy: ${dayMeta.userProfile.energy ?? "-"}`);
    lines.push(`- Priority: ${dayMeta.userProfile.priority || "-"}`);
    lines.push(`- Focus Hours (planned): ${dayMeta.focusHours}`);
  }

  if (dayMeta.customSubjects?.length){
    lines.push("");
    lines.push("Custom Subjects");
    dayMeta.customSubjects.forEach(s => 
      lines.push(`- ${s.name} (${s.checklist.length} checklist items)`)
    );
  }

  if (dayMeta.dice){
    lines.push("");
    lines.push("Focus Allocation (Dice)");
    Object.keys(dayMeta.dice).forEach(k => 
      lines.push(`- ${k}: ${dayMeta.dice[k]}%`)
    );
  }

  if (sessionLogs.length){
    lines.push("");
    lines.push("Focus Sessions (Planned vs Actual)");
    sessionLogs.forEach(s=>{
      const actualMin = (s.actualSeconds / 60).toFixed(1);
      lines.push(`- ${s.name}: planned ${s.plannedMinutes} min, actual ${actualMin} min (${s.status})`);
      if (s.notes) lines.push(`  Notes: ${s.notes}`);
      if (s.questions?.length) lines.push(`  Qs/Todos: ${s.questions.join(" | ")}`);
    });
  }

  const morning = notes.find(n => n.type === "reflection-morning");
  if (morning){
    lines.push("");
    lines.push(formatQA("Morning Reflection", morning.content));
  }

  const afternoon = notes.find(n => n.type === "reflection-afternoon");
  if (afternoon){
    lines.push(formatQA("Afternoon Reflection", afternoon.content));
  }

  const knowledge = notes.filter(n => n.type === "knowledge");
  if (knowledge.length){
    lines.push("Knowledge Questions");
    knowledge.forEach(k=>{
      lines.push(`- Q: ${k.content.question}`);
      lines.push(`  A: ${k.content.answer || "(no answer)"}`);
    });
    lines.push("");
  }

  const curios = notes.filter(n => n.type === "curiosity");
  if (curios.length){
    lines.push("Curiosity");
    curios.forEach(c=>{
      if (c.meta?.prompt) lines.push(`- Prompt: ${c.meta.prompt}`);
      lines.push(`  Response: ${c.content || "(no response)"}`);
    });
    lines.push("");
  }

  const journals = notes.filter(n => n.type === "journal");
  if (journals.length){
    lines.push("Journals");
    journals.forEach(j=>{
      lines.push(`- ${j.title}:`);
      lines.push(`${j.content || "(no entry)"}`);
    });
    lines.push("");
  }

  const eod = notes.find(n => n.type === "eod");
  if (eod){
    lines.push("End of Day");
    lines.push(`- Gratitude: ${eod.content.grat || "-"}`);
    lines.push(`- Lessons: ${eod.content.lessons || "-"}`);
    lines.push(`- Plan for tomorrow: ${eod.content.plan || "-"}`);
    lines.push("");
  }

  const remainingActs = Object.keys(questionsBacklog || {});
  if (remainingActs.length){
    lines.push("Carry-over Questions (next sessions)");
    remainingActs.forEach(k=>{
      const arr = questionsBacklog[k] || [];
      if (arr.length) lines.push(`- ${k}: ${arr.join(" | ")}`);
    });
    lines.push("");
  }

  lines.push("Meals & Food Challenges");
  lines.push("Planned meals:");
  appConfig.meals.forEach(m => 
    lines.push(`- ${m.label} @ ${m.time}: ${m.macro || "-"}`)
  );

  if (appConfig.foodChallenges?.length){
    lines.push("Challenges:");
    appConfig.foodChallenges.forEach(c => lines.push(`- ${c}`));
  }

  if (appConfig.fasting){
    lines.push(`Fasting: Yes (Iftar ${appConfig.iftarTime}, Suhoor ${appConfig.suhoorTime})`);
  } else {
    lines.push("Fasting: No");
  }

  lines.push("");
  lines.push("Summary generated by Dark Blue Reset");

  return lines.join("\n");
}

function showDownload(){
  clearUI(); 
  setProgress();

  const her = dayMeta.userProfile?.name ? `, ${dayMeta.userProfile.name}` : "";
  document.getElementById("text").innerHTML = `🌙 Bravo! Nhark kaml b wa3i${her}. Tsb7i 3la khir 🌙`;
  document.getElementById("subtext").innerHTML = "Download your daily report.";

  const content = buildTxtSummary();
  const blob = new Blob([content], {type:"text/plain;charset=utf-8"});
  const url = URL.createObjectURL(blob);

  const a = document.createElement("a");
  a.href = url;
  a.download = `dark-blue-reset-day1-${new Date().toISOString().slice(0,10)}.txt`;
  a.innerText = "⬇️ Download report (.txt)";
  a.className = "pill";
  a.style.display = "inline-block";
  a.style.margin = "8px auto";
  a.style.textAlign = "center";

  const res = document.getElementById("result");
  res.style.display = "block";
  res.appendChild(a);

  document.getElementById("buttons").appendChild(
    button("Restart", ()=>location.reload(), "secondary")
  );
}
